### ISSUE TITLE
#2 Horse/Donkey texture

### ISSUE THREAD

**Issue by ORPHEDEUUS** [OffsetMods538/Better-Frost-Walker#5]
Mod indirectly breaks the texture placement on donkeys and horses. 
Noticeably, if the horse texture is intact, then donkey texture is broken, hence vise-versa.

**Comment by OffsetMonkey538** [comment]
Is this actually an issue? This seems to be totally unrelated and was closed right after it was made

**Comment by ORPHEDEUUS** [comment]
yeah my ass mistook your mod for another one my bad g
