### ISSUE TITLE
[Crash] Crash while walking on powder snow with Depth Strider III

### ISSUE THREAD

**Issue by SlayerTheChikken** [OffsetMods538/Better-Frost-Walker#6]
For some reason this mod is crashing the game while walking on powder snow with depth strider enchant on the boots.
[crash-2023-09-15_18.02.28-client.txt](https://github.com/OffsetMods538/Better-Frost-Walker/files/12624070/crash-2023-09-15_18.02.28-client.txt)

**Comment by OffsetMonkey538** [comment]
Ah, I think I see what's wrong.

**Comment by OffsetMonkey538** [comment]
Could you try the 1.19.2 artifact from [here](https://github.com/OffsetMods538/Better-Frost-Walker/actions/runs/6206643368)? Click on `Artifacts`, that should download an `Artifacts.zip` file. Extract the zip file and copy the `.jar` file with the shortest name into your mods folder

**Comment by SlayerTheChikken** [comment]
As soon as I can I will try it, should be tomorrow sometime

**Comment by SlayerTheChikken** [comment]
Testing now

**Comment by SlayerTheChikken** [comment]
Seems to be fixed (:

**Comment by OffsetMonkey538** [comment]
Nice! I'll publish to modrinth once I get back from school.

**Comment by OffsetMonkey538** [comment]
Oh sorry, I forgot todo it yesterday lol. I'll try to remember today lol

**Comment by OffsetMonkey538** [comment]
Remember I have! Seems like I made this project before the template with a publish workflow, so I'll add that quickly

**Comment by OffsetMonkey538** [comment]
ok uhh I think I got the stuff working... https://modrinth.com/mod/better-frost-walker/version/1.1.2
